#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

APP_CONFIG_EXAMPLE="config/.config.example.php"
APP_PROFILE_EXAMPLE="config/appprofile.example.php"
APP_CONFIG_FILE="config/.config.php"
APP_PROFILE_FILE="config/appprofile.php"
ENV_FILE=".env"
COMPOSE_OVERRIDE_FILE="docker-compose.override.yml"
COMPOSE_OVERRIDE_MARKER="# Generated by install.sh for SSPanel-UIM Docker HTTPS mode."
INSTALL_LOCK="storage/.install_lock"
PROCESS_LOCK_FILE="storage/.install_in_progress"
PROCESS_LOCK_DIR="storage/.install_in_progress.d"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-.}")" && pwd -P)"
INSTALL_DIR="$SCRIPT_DIR"
INSTALL_MODE="${SSPANEL_INSTALL_MODE:-install}"

HTTPS_ENABLED="true"
HTTP_PORT="80"
HTTPS_PORT="443"
TZ="Asia/Shanghai"
CADDY_SITE_ADDRESS=""
COOKIE_SECURE="true"
BASE_URL=""

APP_NAME="EzIPLC"
APP_DOMAIN=""
ADMIN_EMAIL=""
ADMIN_PASSWORD=""
DB_DATABASE=""
DB_USERNAME=""
DB_PASSWORD=""
DB_ROOT_PASSWORD=""
REDIS_PASSWORD=""
APP_KEY=""
MU_KEY=""
CREDENTIALS_FILE=""
RECOVERY_CREDENTIALS_FILE=""
ADMIN_PASSWORD_RECOVERABLE="false"

CURRENT_STAGE="启动安装程序"
INSTALL_SUCCEEDED="false"
FALLBACK_LOCK_HELD="false"
BUILD_STASH_DIR=""
STASHED_PATHS=()
STASHED_FILES=()
TEMP_FILES=()

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ "${TERM:-}" != "dumb" ]; then
    BLUE=$'\033[34m'
    GREEN=$'\033[32m'
    YELLOW=$'\033[33m'
    RED=$'\033[31m'
    GRAY=$'\033[90m'
    RESET=$'\033[0m'
    INFO_MARK="i"
    OK_MARK="✓"
    WARN_MARK="!"
    ERROR_MARK="✗"
else
    BLUE=""
    GREEN=""
    YELLOW=""
    RED=""
    GRAY=""
    RESET=""
    INFO_MARK="i"
    OK_MARK="OK"
    WARN_MARK="WARN"
    ERROR_MARK="ERROR"
fi

info() {
    printf '%b%s%b %s\n' "$BLUE" "$INFO_MARK" "$RESET" "$*"
}

success() {
    printf '%b%s%b %s\n' "$GREEN" "$OK_MARK" "$RESET" "$*"
}

warn() {
    printf '%b%s%b %s\n' "$YELLOW" "$WARN_MARK" "$RESET" "$*" >&2
}

die() {
    printf '%b%s%b %s\n' "$RED" "$ERROR_MARK" "$RESET" "$*" >&2
    exit 1
}

show_step() {
    CURRENT_STAGE="$2"
    printf '\n%b[%s/8]%b %s\n' "$BLUE" "$1" "$RESET" "$2"
    printf '%b%s%b\n' "$GRAY" '────────────────────────────────────────' "$RESET"
}

banner() {
    if [ "${TERM:-}" = "dumb" ]; then
        cat <<'EOF'
========================================
       EzIPLC 面板智能安装向导
       Secure Docker Deployment
========================================
EOF
        return 0
    fi

    cat <<'EOF'
╭────────────────────────────────────────╮
│       EzIPLC 面板智能安装向导          │
│       Secure Docker Deployment         │
╰────────────────────────────────────────╯
EOF
}

restore_build_files() {
    local index
    local path
    local stash_file

    for index in "${!STASHED_PATHS[@]}"; do
        path="${STASHED_PATHS[$index]:-}"
        stash_file="${STASHED_FILES[$index]:-}"
        if [ -z "$path" ] || [ -z "$stash_file" ]; then
            warn "跳过不完整的构建暂存记录：${index}。"
            continue
        fi
        if [ -e "$stash_file" ]; then
            mkdir -p "$(dirname "$path")"
            mv -- "$stash_file" "$path"
        fi
    done

    if [ -n "$BUILD_STASH_DIR" ] && [ -d "$BUILD_STASH_DIR" ]; then
        rmdir "$BUILD_STASH_DIR" 2>/dev/null || true
    fi

    BUILD_STASH_DIR=""
    STASHED_PATHS=()
    STASHED_FILES=()
}

cleanup_temp_files() {
    local path
    for path in "${TEMP_FILES[@]}"; do
        [ ! -e "$path" ] || rm -f -- "$path"
    done
}

failure_report() {
    printf '\n%b%s 安装失败%b\n' "$RED" "$ERROR_MARK" "$RESET" >&2
    printf '失败阶段：%s\n' "$CURRENT_STAGE" >&2

    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        printf '\nDocker Compose 状态：\n' >&2
        docker compose ps >&2 2>/dev/null || true
    fi

    if [ -n "$RECOVERY_CREDENTIALS_FILE" ] && [ -f "$RECOVERY_CREDENTIALS_FILE" ]; then
        printf '\n恢复凭据已保留：%s\n' "$RECOVERY_CREDENTIALS_FILE" >&2
        printf '修复问题后可运行：sudo bash bootstrap.sh --resume\n' >&2
    fi

    cat >&2 <<'EOF'

建议的排查命令：
  docker compose ps
  docker compose logs --tail=200 caddy
  docker compose logs --tail=200 app
  docker compose logs --tail=200 mariadb

脚本没有删除任何 Docker volume。修复问题前请保留 .env、config/.config.php、
config/appprofile.php 和现有数据卷。
EOF
}

on_exit() {
    local status=$?
    trap - EXIT

    restore_build_files || true
    cleanup_temp_files || true
    if [ "$FALLBACK_LOCK_HELD" = "true" ]; then
        rmdir "$PROCESS_LOCK_DIR" 2>/dev/null || true
    fi

    if [ "$status" -ne 0 ] && [ "$INSTALL_SUCCEEDED" != "true" ]; then
        failure_report
    fi

    exit "$status"
}

trap on_exit EXIT

require_root() {
    [ "${EUID:-$(id -u)}" -eq 0 ] || die "install.sh 必须以 root 运行。请通过 bootstrap.sh 启动安装。"
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "缺少必需命令：$1"
}

require_runtime() {
    require_command docker
    require_command openssl
    require_command curl
    docker compose version >/dev/null 2>&1 || die "需要 Docker Compose v2 插件，请使用 'docker compose'。"
    docker info >/dev/null 2>&1 || die "Docker daemon 不可用，请检查 systemctl status docker。"
    [ -f "$APP_CONFIG_EXAMPLE" ] || die "缺少模板：${APP_CONFIG_EXAMPLE}"
    [ -f "$APP_PROFILE_EXAMPLE" ] || die "缺少模板：${APP_PROFILE_EXAMPLE}"
    [ -f docker-compose.yml ] || die "缺少 docker-compose.yml。"
}

acquire_install_lock() {
    mkdir -p storage

    if command -v flock >/dev/null 2>&1; then
        exec 9>"$PROCESS_LOCK_FILE"
        flock -n 9 || die "检测到另一个安装进程正在运行，本次安装已终止。"
        return 0
    fi

    if ! mkdir "$PROCESS_LOCK_DIR" 2>/dev/null; then
        die "检测到另一个安装进程或遗留锁 ${PROCESS_LOCK_DIR}，请确认没有安装进程后再处理。"
    fi
    FALLBACK_LOCK_HELD="true"
}

compose_has_containers() {
    [ -n "$(DB_PASSWORD=probe DB_ROOT_PASSWORD=probe docker compose ps -aq 2>/dev/null || true)" ]
}

has_mariadb_volume() {
    local project_name

    project_name="$(basename "$INSTALL_DIR" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_-]+/-/g; s/^[^a-z0-9]+//')"
    [ -n "$(docker volume ls -q \
        --filter "label=com.docker.compose.project=${project_name}" \
        --filter 'label=com.docker.compose.volume=mariadb_data' \
        2>/dev/null || true)" ]
}

has_installation_files() {
    [ -f "$ENV_FILE" ] \
        || [ -f "$APP_CONFIG_FILE" ] \
        || [ -f "$APP_PROFILE_FILE" ] \
        || [ -f "$COMPOSE_OVERRIDE_FILE" ] \
        || [ -f "$INSTALL_LOCK" ]
}

guard_existing_installation() {
    case "$INSTALL_MODE" in
        install)
            if has_installation_files || compose_has_containers || has_mariadb_volume; then
                if [ -f "$ENV_FILE" ] && [ -f "$APP_CONFIG_FILE" ] && [ ! -e "$INSTALL_LOCK" ]; then
                    die "检测到未完成的安装。请保留现有配置和 Docker volume，并使用 bootstrap.sh --resume。"
                fi
                die "检测到已有安装，为避免数据库凭据失配，本次安装已安全终止。请使用 bootstrap.sh --upgrade。"
            fi
            ;;
        reinstall)
            [ "${SSPANEL_REINSTALL_CONFIRMED:-}" = "1" ] \
                || die "重装必须通过 bootstrap.sh --reinstall 的确认流程启动。"
            if compose_has_containers || has_mariadb_volume; then
                die "检测到现有容器或 MariaDB volume。脚本不会自动删除生产数据，请先备份并手工处理。"
            fi
            ;;
        resume)
            [ -f "$ENV_FILE" ] || die "恢复模式要求现有 .env。"
            [ -f "$APP_CONFIG_FILE" ] || die "恢复模式要求现有 config/.config.php。"
            [ ! -e "$INSTALL_LOCK" ] || die "检测到 storage/.install_lock；已完成的安装不能使用 --resume。"
            ;;
        *) die "不支持的安装模式：${INSTALL_MODE}" ;;
    esac
}

trim() {
    local value="$*"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf '%s' "$value"
}

read_tty() {
    local variable_name="$1"
    local prompt="$2"
    local secret="${3:-false}"
    local input_value=""

    [ -r /dev/tty ] || die "当前会话没有可用的 /dev/tty，无法安全读取交互输入。"

    if [ "$secret" = "true" ]; then
        IFS= read -r -s -p "$prompt" input_value </dev/tty
        printf '\n' >/dev/tty
    else
        IFS= read -r -p "$prompt" input_value </dev/tty
    fi
    printf -v "$variable_name" '%s' "$input_value"
}

prompt_site_name() {
    local value

    while true; do
        read_tty value "站点名称 [EzIPLC]: "
        value="$(trim "$value")"
        APP_NAME="${value:-EzIPLC}"
        [ -n "$APP_NAME" ] && return 0
    done
}

valid_domain() {
    [[ "$1" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]]
}

prompt_domain() {
    local value

    while true; do
        read_tty value "站点域名（例如 panel.example.com）: "
        value="$(trim "$value" | tr '[:upper:]' '[:lower:]')"
        if ! valid_domain "$value"; then
            warn "请输入纯域名，不要包含 http://、https://、端口、路径或空格。"
            continue
        fi
        APP_DOMAIN="$value"
        return 0
    done
}

valid_email() {
    [[ "$1" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

prompt_admin_email() {
    local value

    while true; do
        read_tty value "管理员邮箱: "
        value="$(trim "$value")"
        if ! valid_email "$value"; then
            warn "管理员邮箱格式不正确，请重新输入。"
            continue
        fi
        ADMIN_EMAIL="$value"
        return 0
    done
}

prompt_admin_password() {
    local first
    local second

    while true; do
        read_tty first "管理员密码（至少 12 个字符）: " "true"
        if [ "${#first}" -lt 12 ]; then
            warn "管理员密码至少需要 12 个字符。"
            continue
        fi
        read_tty second "再次输入管理员密码: " "true"
        if [ "$first" != "$second" ]; then
            warn "两次输入的密码不一致，请重新输入。"
            continue
        fi
        ADMIN_PASSWORD="$first"
        ADMIN_PASSWORD_RECOVERABLE="true"
        return 0
    done
}

confirm_install() {
    local answer

    printf '\n%b安装确认%b\n' "$BLUE" "$RESET"
    printf '  站点名称：%s\n' "$APP_NAME"
    printf '  站点域名：%s\n' "$APP_DOMAIN"
    printf '  管理员账号：%s\n' "$ADMIN_EMAIL"
    printf '  安装目录：%s\n' "$INSTALL_DIR"
    printf '  HTTPS 模式：Caddy 自动 HTTPS（80/443）\n'
    printf '  时区：%s\n' "$TZ"
    printf '%b所有密码和内部密钥均已隐藏。%b\n' "$GRAY" "$RESET"

    read_tty answer "确认开始安装？[Y/n] "
    case "$(trim "$answer")" in
        ""|y|Y|yes|YES) return 0 ;;
        *)
            info "安装已取消，尚未写入配置或启动容器。"
            exit 0
            ;;
    esac
}

random_hex() {
    local bytes="$1"
    local expected_length="$2"
    local value

    value="$(openssl rand -hex "$bytes")" || die "openssl rand 生成随机值失败。"
    [[ "$value" =~ ^[0-9a-f]+$ ]] || die "随机值包含非法字符。"
    [ "${#value}" -eq "$expected_length" ] || die "随机值长度不符合预期。"
    printf '%s' "$value"
}

validate_hex_value() {
    local label="$1"
    local value="$2"
    local expected_length="$3"

    [ -n "$value" ] || die "${label} 不能为空。"
    [[ "$value" =~ ^[0-9a-f]+$ ]] || die "${label} 只能包含小写十六进制字符。"
    [ "${#value}" -eq "$expected_length" ] || die "${label} 长度不符合预期。"
}

generate_credentials() {
    DB_DATABASE="sspanel_$(random_hex 5 10)"
    DB_USERNAME="ssu_$(random_hex 6 12)"
    DB_PASSWORD="$(random_hex 24 48)"
    DB_ROOT_PASSWORD="$(random_hex 24 48)"
    REDIS_PASSWORD="$(random_hex 24 48)"
    APP_KEY="$(random_hex 32 64)"
    MU_KEY="$(random_hex 32 64)"

    [[ "$DB_DATABASE" =~ ^[a-z0-9_]+$ ]] || die "数据库名包含非法字符。"
    [[ "$DB_USERNAME" =~ ^[a-z0-9_]+$ ]] || die "数据库用户名包含非法字符。"
    [ "${#DB_DATABASE}" -ge 16 ] && [ "${#DB_DATABASE}" -le 20 ] || die "数据库名长度不符合预期。"
    [ "${#DB_USERNAME}" -le 32 ] || die "数据库用户名超过 MariaDB 安全长度。"
    validate_hex_value "数据库密码" "$DB_PASSWORD" 48
    validate_hex_value "数据库 root 密码" "$DB_ROOT_PASSWORD" 48
    validate_hex_value "Redis 密码" "$REDIS_PASSWORD" 48
    validate_hex_value "App Key" "$APP_KEY" 64
    validate_hex_value "muKey" "$MU_KEY" 64

    CADDY_SITE_ADDRESS="$APP_DOMAIN"
    BASE_URL="https://${APP_DOMAIN}"
    success "数据库、Redis、App Key 和 muKey 已使用 OpenSSL 安全生成。"
}

dotenv_quote() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

php_string() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

atomic_write() {
    local target="$1"
    local mode="$2"
    local directory
    local filename
    local temp_file

    directory="$(dirname "$target")"
    filename="$(basename "$target")"
    mkdir -p "$directory"
    temp_file="$(mktemp "${directory}/.${filename}.tmp.XXXXXX")"
    TEMP_FILES+=("$temp_file")
    cat > "$temp_file"
    chmod "$mode" "$temp_file"
    mv -f -- "$temp_file" "$target"
}

read_env_value() {
    local key="$1"
    local value

    value="$(sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1)"
    [ -n "$value" ] || die "现有 .env 缺少 ${key}。"
    case "$value" in
        \'*\') value="${value#\'}"; value="${value%\'}" ;;
        \"*\") value="${value#\"}"; value="${value%\"}" ;;
    esac
    value="${value//\\\'/\'}"
    value="${value//\\\\/\\}"
    printf '%s' "$value"
}

read_php_hex_value() {
    local key="$1"
    local value

    value="$(sed -n "s/^[[:space:]]*\\\$_ENV\['${key}'\][[:space:]]*=[[:space:]]*'\([0-9a-f]*\)'.*/\1/p" "$APP_CONFIG_FILE" | tail -n 1)"
    [ -n "$value" ] || die "现有 config/.config.php 缺少可恢复的 ${key}。"
    printf '%s' "$value"
}

credential_field() {
    local label="$1"
    local source_file="$2"

    sed -n "s/^${label}: //p" "$source_file" | head -n 1
}

find_recovery_credentials_file() {
    local candidate
    local matched=""

    for candidate in /root/eziplc-panel-recovery-*.txt; do
        [ -f "$candidate" ] || continue
        if grep -Fqx "安装目录: ${INSTALL_DIR}" "$candidate"; then
            matched="$candidate"
        fi
    done
    printf '%s' "$matched"
}

load_existing_credentials() {
    local recoverable

    APP_DOMAIN="$(read_env_value APP_DOMAIN)"
    APP_NAME="$(read_env_value APP_NAME)"
    HTTPS_ENABLED="$(read_env_value HTTPS_ENABLED)"
    HTTP_PORT="$(read_env_value HTTP_PORT)"
    HTTPS_PORT="$(read_env_value HTTPS_PORT)"
    CADDY_SITE_ADDRESS="$(read_env_value CADDY_SITE_ADDRESS)"
    DB_DATABASE="$(read_env_value DB_DATABASE)"
    DB_USERNAME="$(read_env_value DB_USERNAME)"
    DB_PASSWORD="$(read_env_value DB_PASSWORD)"
    DB_ROOT_PASSWORD="$(read_env_value DB_ROOT_PASSWORD)"
    REDIS_PASSWORD="$(read_env_value REDIS_PASSWORD)"
    TZ="$(read_env_value TZ)"
    APP_KEY="$(read_php_hex_value key)"
    MU_KEY="$(read_php_hex_value muKey)"
    BASE_URL="https://${APP_DOMAIN}"

    valid_domain "$APP_DOMAIN" || die "现有 .env 中的 APP_DOMAIN 无效。"
    validate_hex_value "数据库密码" "$DB_PASSWORD" 48
    validate_hex_value "数据库 root 密码" "$DB_ROOT_PASSWORD" 48
    validate_hex_value "Redis 密码" "$REDIS_PASSWORD" 48
    validate_hex_value "App Key" "$APP_KEY" 64
    validate_hex_value "muKey" "$MU_KEY" 64

    RECOVERY_CREDENTIALS_FILE="$(find_recovery_credentials_file)"
    if [ -n "$RECOVERY_CREDENTIALS_FILE" ]; then
        recoverable="$(credential_field "管理员密码可恢复" "$RECOVERY_CREDENTIALS_FILE")"
        ADMIN_EMAIL="$(credential_field "管理员账号" "$RECOVERY_CREDENTIALS_FILE")"
        if [ "$recoverable" = "yes" ]; then
            ADMIN_PASSWORD="$(credential_field "管理员密码" "$RECOVERY_CREDENTIALS_FILE")"
            ADMIN_PASSWORD_RECOVERABLE="true"
        fi
    fi

    success "已读取现有配置；数据库、Redis、App Key 和 muKey 均保持不变。"
}

write_env_file() {
    atomic_write "$ENV_FILE" 0600 <<EOF
# Generated by install.sh. Do not commit this file.
APP_DOMAIN=$(dotenv_quote "$APP_DOMAIN")
APP_NAME=$(dotenv_quote "$APP_NAME")
HTTPS_ENABLED=$(dotenv_quote "$HTTPS_ENABLED")
HTTP_PORT=$(dotenv_quote "$HTTP_PORT")
HTTPS_PORT=$(dotenv_quote "$HTTPS_PORT")
CADDY_SITE_ADDRESS=$(dotenv_quote "$CADDY_SITE_ADDRESS")

DB_DATABASE=$(dotenv_quote "$DB_DATABASE")
DB_USERNAME=$(dotenv_quote "$DB_USERNAME")
DB_PASSWORD=$(dotenv_quote "$DB_PASSWORD")
DB_ROOT_PASSWORD=$(dotenv_quote "$DB_ROOT_PASSWORD")

REDIS_PASSWORD=$(dotenv_quote "$REDIS_PASSWORD")
TZ=$(dotenv_quote "$TZ")
EOF
}

write_config_file() {
    local temp_file
    local key_value
    local mu_key_value
    local app_name_value
    local base_url_value

    key_value="$(php_string "$APP_KEY")"
    mu_key_value="$(php_string "$MU_KEY")"
    app_name_value="$(php_string "$APP_NAME")"
    base_url_value="$(php_string "$BASE_URL")"

    temp_file="$(mktemp "config/.config.php.tmp.XXXXXX")"
    TEMP_FILES+=("$temp_file")

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            "\$_ENV['key'] ="*) printf "\$_ENV['key'] = %s;     // Generated by install.sh\n" "$key_value" ;;
            "\$_ENV['appName'] ="*) printf "\$_ENV['appName'] = %s;         // Generated by install.sh\n" "$app_name_value" ;;
            "\$_ENV['baseUrl'] ="*) printf "\$_ENV['baseUrl'] = %s; // Generated by install.sh\n\$_ENV['cookie_secure'] = true;        // Generated by install.sh\n" "$base_url_value" ;;
            "\$_ENV['muKey'] ="*) printf "\$_ENV['muKey'] = %s;           // Generated by install.sh\n" "$mu_key_value" ;;
            "\$_ENV['db_host'] ="*) printf "\$_ENV['db_host'] = 'mariadb';\n" ;;
            "\$_ENV['db_socket'] ="*) printf "\$_ENV['db_socket'] = '';\n" ;;
            "\$_ENV['db_database'] ="*) printf "\$_ENV['db_database'] = %s; // Generated by install.sh\n" "$(php_string "$DB_DATABASE")" ;;
            "\$_ENV['db_username'] ="*) printf "\$_ENV['db_username'] = %s;    // Generated by install.sh\n" "$(php_string "$DB_USERNAME")" ;;
            "\$_ENV['db_password'] ="*) printf "\$_ENV['db_password'] = %s; // Generated by install.sh\n" "$(php_string "$DB_PASSWORD")" ;;
            "\$_ENV['db_port'] ="*) printf "\$_ENV['db_port'] = '3306';        // Generated by install.sh\n" ;;
            "\$_ENV['redis_host'] ="*) printf "\$_ENV['redis_host'] = 'redis';    // Generated by install.sh\n" ;;
            "\$_ENV['redis_port'] ="*) printf "\$_ENV['redis_port'] = 6379;           // Generated by install.sh\n" ;;
            "\$_ENV['redis_username'] ="*) printf "\$_ENV['redis_username'] = '';         // Generated by install.sh\n" ;;
            "\$_ENV['redis_password'] ="*) printf "\$_ENV['redis_password'] = %s;         // Generated by install.sh\n" "$(php_string "$REDIS_PASSWORD")" ;;
            "\$_ENV['timeZone'] ="*) printf "\$_ENV['timeZone'] = %s;        // Generated by install.sh\n" "$(php_string "$TZ")" ;;
            *) printf '%s\n' "$line" ;;
        esac
    done < "$APP_CONFIG_EXAMPLE" > "$temp_file"

    chmod 0644 "$temp_file"
    mv -f -- "$temp_file" "$APP_CONFIG_FILE"
}

write_appprofile_file() {
    atomic_write "$APP_PROFILE_FILE" 0644 < "$APP_PROFILE_EXAMPLE"
}

write_compose_override() {
    atomic_write "$COMPOSE_OVERRIDE_FILE" 0644 <<EOF
${COMPOSE_OVERRIDE_MARKER}
services:
  caddy:
    ports:
      - "\${HTTPS_PORT:-443}:443"
EOF
}

export_compose_environment() {
    export APP_DOMAIN APP_NAME HTTPS_ENABLED HTTP_PORT HTTPS_PORT CADDY_SITE_ADDRESS
    export DB_DATABASE DB_USERNAME DB_PASSWORD DB_ROOT_PASSWORD REDIS_PASSWORD TZ
}

validate_compose_config() {
    export_compose_environment
    docker compose config >/dev/null
    success "Docker Compose 配置校验通过。"
}

stash_for_build() {
    local path="$1"
    local stash_file

    [ -e "$path" ] || return 0
    if [ -z "$BUILD_STASH_DIR" ]; then
        BUILD_STASH_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sspanel-install-build.XXXXXX")"
        chmod 0700 "$BUILD_STASH_DIR"
    fi

    stash_file="${BUILD_STASH_DIR}/$(printf '%s' "$path" | tr '/\\' '__')"
    mv -- "$path" "$stash_file"
    STASHED_PATHS+=("$path")
    STASHED_FILES+=("$stash_file")
}

build_images() {
    stash_for_build "$ENV_FILE"
    stash_for_build "$APP_CONFIG_FILE"
    stash_for_build "$APP_PROFILE_FILE"
    docker compose build
    restore_build_files
}

docker_compose_up() {
    local services=("$@")
    docker compose up -d "${services[@]}"
}

wait_for_health() {
    local service="$1"
    local timeout_seconds="$2"
    local started_at
    local container_id
    local status

    started_at="$(date +%s)"
    while true; do
        container_id="$(docker compose ps -q "$service" | sed -n '1p')"
        if [ -n "$container_id" ]; then
            status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"
            case "$status" in
                healthy|running)
                    success "${service} 已就绪。"
                    return 0
                    ;;
                unhealthy|exited|dead)
                    die "${service} 状态为 ${status}。"
                    ;;
            esac
        fi

        if [ $(( "$(date +%s)" - started_at )) -ge "$timeout_seconds" ]; then
            die "等待 ${service} 就绪超时。"
        fi
        sleep 3
    done
}

ensure_app_autoload() {
    docker compose exec -T app test -f vendor/autoload.php \
        || die "app 容器缺少 vendor/autoload.php，请检查 Docker 构建日志。"
}

run_init_command() {
    info "执行初始化命令：php xcat $*"
    docker compose exec -T app php xcat "$@"
}

run_mariadb_root_sql() {
    local sql="$1"
    docker compose exec -T mariadb sh -c \
        'exec mariadb --batch --raw --skip-column-names -u root --password="$MARIADB_ROOT_PASSWORD" "$MARIADB_DATABASE" -e "$1"' \
        sh "$sql"
}

ensure_user_ga_enable_column() {
    local column_count

    info "检查 Docker 兼容字段 user.ga_enable。"
    column_count="$(run_mariadb_root_sql "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' AND COLUMN_NAME = 'ga_enable';" | tr -d '[:space:]')" \
        || die "检查 user.ga_enable 字段失败。"

    case "$column_count" in
        1) success "user.ga_enable 已存在。" ;;
        0)
            run_mariadb_root_sql "ALTER TABLE \`user\` ADD COLUMN \`ga_enable\` tinyint(1) unsigned NOT NULL DEFAULT 0;"
            success "user.ga_enable 兼容字段已添加。"
            ;;
        *) die "检查 user.ga_enable 返回意外结果：${column_count}" ;;
    esac
}

create_admin() {
    local output
    local admin_count

    info "创建管理员账号（密码不会写入日志）。"
    if ! output="$(docker compose exec -T app php xcat Tool createAdmin "$ADMIN_EMAIL" "$ADMIN_PASSWORD" 2>&1)"; then
        printf '%s\n' "$output" >&2
        die "管理员创建命令执行失败，首次安装不能继续。"
    fi
    printf '%s\n' "$output"
    printf '%s\n' "$output" | grep -Fq '创建成功' \
        || die "管理员创建命令未返回成功结果，首次安装不能继续。"

    admin_count="$(run_mariadb_root_sql "SELECT COUNT(*) FROM \`user\` WHERE email = '${ADMIN_EMAIL}' AND is_admin = 1;" | tr -d '[:space:]')" \
        || die "无法验证管理员数据库记录。"
    [ "$admin_count" = "1" ] || die "管理员数据库记录验证失败，匹配数量为 ${admin_count:-0}。"
    success "管理员账号已创建。"
}

ensure_admin_for_resume() {
    local admin_count
    local existing_admin_email

    admin_count="$(run_mariadb_root_sql "SELECT COUNT(*) FROM \`user\` WHERE is_admin = 1;" | tr -d '[:space:]')" \
        || die "无法检查现有管理员账号。"
    [[ "$admin_count" =~ ^[0-9]+$ ]] || die "管理员数量检查返回意外结果：${admin_count:-empty}。"

    if [ "$admin_count" -gt 0 ]; then
        existing_admin_email="$(run_mariadb_root_sql "SELECT email FROM \`user\` WHERE is_admin = 1 ORDER BY id LIMIT 1;" | sed -n '1p')" \
            || die "无法读取现有管理员账号。"
        valid_email "$ADMIN_EMAIL" || ADMIN_EMAIL="$existing_admin_email"
        success "检测到现有管理员账号，跳过重复创建。"
        write_recovery_credentials_file
        return 0
    fi

    if ! valid_email "$ADMIN_EMAIL" \
        || [ "$ADMIN_PASSWORD_RECOVERABLE" != "true" ] \
        || [ "${#ADMIN_PASSWORD}" -lt 12 ]; then
        warn "未找到现有管理员和可恢复的管理员凭据，请创建管理员。"
        prompt_admin_email
        prompt_admin_password
        write_recovery_credentials_file
    fi
    create_admin
}

verify_containers() {
    local timeout_seconds=60
    local started_at
    local service
    local container_id
    local status
    local health
    local effective_status
    local exit_code
    local all_ready
    local pending_service
    local pending_status
    local pending_exit_code

    started_at="$(date +%s)"
    while true; do
        all_ready="true"
        pending_service=""
        pending_status=""
        pending_exit_code=""

        for service in mariadb redis app nginx caddy scheduler; do
            status=""
            health=""
            effective_status="unknown"
            exit_code="unknown"
            container_id="$(docker compose ps -aq "$service" | sed -n '1p')"
            if [ -z "$container_id" ]; then
                all_ready="false"
                effective_status="not-found"
                exit_code="unknown"
            else
                status="$(docker inspect --format '{{.State.Status}}' "$container_id" 2>/dev/null || true)"
                health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}' "$container_id" 2>/dev/null || true)"
                exit_code="$(docker inspect --format '{{.State.ExitCode}}' "$container_id" 2>/dev/null || true)"
                effective_status="${health:-${status:-unknown}}"

                case "$effective_status" in
                    running|healthy) continue ;;
                esac
                all_ready="false"
            fi

            pending_service="$service"
            pending_status="$effective_status"
            pending_exit_code="$exit_code"

            case "${status:-$effective_status}" in
                restarting|exited|dead)
                    docker compose ps >&2 || true
                    docker compose logs --tail=100 "$service" >&2 || true
                    die "${service} 容器状态为 ${status:-$effective_status}，ExitCode=${exit_code:-unknown}。"
                    ;;
            esac
            if [ "$effective_status" = "unhealthy" ]; then
                docker compose ps >&2 || true
                docker compose logs --tail=100 "$service" >&2 || true
                die "${service} 容器状态为 unhealthy，ExitCode=${exit_code:-unknown}。"
            fi
        done

        if [ "$all_ready" = "true" ]; then
            success "全部 Docker 服务均处于 running 或 healthy 状态。"
            return 0
        fi

        if [ $(( "$(date +%s)" - started_at )) -ge "$timeout_seconds" ]; then
            docker compose ps >&2 || true
            docker compose logs --tail=100 "$pending_service" >&2 || true
            die "等待 ${pending_service} 容器就绪超过 ${timeout_seconds} 秒，状态为 ${pending_status:-unknown}，ExitCode=${pending_exit_code:-unknown}。"
        fi
        sleep 3
    done
}

verify_https() {
    local timeout_seconds=180
    local started_at

    info "等待 Caddy 完成 HTTPS 证书申请并验证 ${BASE_URL}。"
    started_at="$(date +%s)"
    while true; do
        if curl --fail --silent --show-error --location \
            --connect-timeout 5 --max-time 15 "${BASE_URL}/" >/dev/null 2>&1; then
            success "HTTPS 访问验证通过。"
            return 0
        fi

        if [ $(( "$(date +%s)" - started_at )) -ge "$timeout_seconds" ]; then
            warn "HTTPS 验证在 ${timeout_seconds} 秒内未通过。"
            warn "请检查域名 DNS、服务器 80/443 端口、防火墙、端口占用，以及 Cloudflare 是否需要临时切换为 DNS-only。"
            return 1
        fi
        sleep 5
    done
}

write_credentials_document() {
    local target="$1"
    local status_label="$2"
    local created_at
    local admin_email_display
    local admin_password_display
    local recoverable_label

    created_at="$(date '+%Y-%m-%d %H:%M:%S %Z')"
    admin_email_display="${ADMIN_EMAIL:-恢复完成后从数据库确认}"
    if [ "$ADMIN_PASSWORD_RECOVERABLE" = "true" ]; then
        admin_password_display="$ADMIN_PASSWORD"
        recoverable_label="yes"
    else
        admin_password_display="未保存在现有配置中；请继续使用原管理员密码"
        recoverable_label="no"
    fi

    atomic_write "$target" 0600 <<EOF
EzIPLC / SSPanel-UIM-Docker 安装凭据
状态: ${status_label}
创建时间: ${created_at}
站点 URL: ${BASE_URL}
安装目录: ${INSTALL_DIR}

管理员账号: ${admin_email_display}
管理员密码可恢复: ${recoverable_label}
管理员密码: ${admin_password_display}

数据库主机: mariadb
数据库端口: 3306
数据库名称: ${DB_DATABASE}
数据库用户: ${DB_USERNAME}
数据库密码: ${DB_PASSWORD}
数据库 root 密码: ${DB_ROOT_PASSWORD}
Redis 密码: ${REDIS_PASSWORD}
App Key: ${APP_KEY}
muKey: ${MU_KEY}
时区: ${TZ}

常用管理命令:
  cd ${INSTALL_DIR}
  docker compose ps
  docker compose logs -f app
  docker compose logs -f caddy
  sudo bash bootstrap.sh --upgrade

数据库备份示例:
  cd ${INSTALL_DIR}
  docker compose exec -T mariadb sh -c 'exec mariadb-dump -u root -p"\$MARIADB_ROOT_PASSWORD" "\$MARIADB_DATABASE"' > /root/sspanel-backup.sql

备份提示:
  同时备份 .env、config/.config.php、config/appprofile.php、数据库导出文件和必要的 Docker volume。
  永远不要随意执行 docker compose down -v。
EOF

    [ "$(stat -c '%a' "$target")" = "600" ] || die "凭据文件权限不是 0600：${target}"
}

write_recovery_credentials_file() {
    local timestamp

    if [ -z "$RECOVERY_CREDENTIALS_FILE" ]; then
        timestamp="$(date '+%Y%m%d-%H%M%S')"
        RECOVERY_CREDENTIALS_FILE="/root/eziplc-panel-recovery-${timestamp}.txt"
    fi
    write_credentials_document "$RECOVERY_CREDENTIALS_FILE" "安装未完成（恢复凭据）"
    success "恢复凭据已安全写入 ${RECOVERY_CREDENTIALS_FILE}（权限 0600）。"
}

finalize_credentials_file() {
    local timestamp

    [ -n "$RECOVERY_CREDENTIALS_FILE" ] || die "恢复凭据文件尚未创建。"
    case "$RECOVERY_CREDENTIALS_FILE" in
        /root/eziplc-panel-recovery-*.txt)
            CREDENTIALS_FILE="${RECOVERY_CREDENTIALS_FILE/eziplc-panel-recovery-/eziplc-panel-credentials-}"
            ;;
        *)
            timestamp="$(date '+%Y%m%d-%H%M%S')"
            CREDENTIALS_FILE="/root/eziplc-panel-credentials-${timestamp}.txt"
            ;;
    esac

    write_credentials_document "$CREDENTIALS_FILE" "安装成功（正式凭据）"
}

remove_recovery_credentials_file() {
    [ -n "$RECOVERY_CREDENTIALS_FILE" ] || return 0
    rm -f -- "$RECOVERY_CREDENTIALS_FILE"
    RECOVERY_CREDENTIALS_FILE=""
}

write_install_lock() {
    atomic_write "$INSTALL_LOCK" 0600 <<EOF
installed_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
domain=${APP_DOMAIN}
EOF
}

print_credentials_summary() {
    if [ "${TERM:-}" = "dumb" ]; then
        printf '\n========== 安装成功 ==========\n'
    else
        printf '\n╭──────────────── 安装成功 ────────────────╮\n'
    fi
    printf '│ 站点地址: %s\n' "$BASE_URL"
    printf '│ 安装目录: %s\n' "$INSTALL_DIR"
    printf '│ 管理员账号: %s\n' "$ADMIN_EMAIL"
    if [ "$ADMIN_PASSWORD_RECOVERABLE" = "true" ]; then
        printf '│ 管理员密码: %s\n' "$ADMIN_PASSWORD"
    else
        printf '│ 管理员密码: 未保存在现有配置中，请继续使用原密码\n'
    fi
    printf '│ 数据库主机: mariadb\n'
    printf '│ 数据库端口: 3306\n'
    printf '│ 数据库名称: %s\n' "$DB_DATABASE"
    printf '│ 数据库用户: %s\n' "$DB_USERNAME"
    printf '│ 数据库密码: %s\n' "$DB_PASSWORD"
    printf '│ 数据库 root 密码: %s\n' "$DB_ROOT_PASSWORD"
    printf '│ Redis 密码: %s\n' "$REDIS_PASSWORD"
    printf '│ App Key: %s\n' "$APP_KEY"
    printf '│ muKey: %s\n' "$MU_KEY"
    printf '│ 时区: %s\n' "$TZ"
    printf '│ 凭据文件: %s\n' "$CREDENTIALS_FILE"
    if [ "${TERM:-}" = "dumb" ]; then
        printf '================================\n'
    else
        printf '╰──────────────────────────────────────────╯\n'
    fi

    warn "以上敏感信息仅显示一次，请立即保存。"
    warn "服务器中的凭据文件权限为 0600。"
    warn "不要将凭据文件发送到聊天、工单或公开仓库。"
}

resume_installation() {
    show_step 1 "检查部分安装状态"
    require_root
    require_runtime
    acquire_install_lock
    guard_existing_installation
    success "确认存在 .env 和 config/.config.php，且尚未写入安装锁。"

    show_step 2 "读取现有配置和恢复凭据"
    load_existing_credentials
    [ -f "$APP_PROFILE_FILE" ] || write_appprofile_file
    [ -f "$COMPOSE_OVERRIDE_FILE" ] || write_compose_override
    write_recovery_credentials_file
    validate_compose_config

    show_step 3 "重建 Docker 镜像"
    build_images
    success "Docker 镜像重建完成，未重新生成任何凭据。"

    show_step 4 "启动现有服务"
    docker_compose_up mariadb redis
    wait_for_health mariadb 240
    wait_for_health redis 120
    docker_compose_up app nginx caddy scheduler
    ensure_app_autoload

    show_step 5 "更新数据库结构"
    run_init_command Migration latest

    show_step 6 "确认管理员账号"
    ensure_admin_for_resume

    show_step 7 "验证 Docker 服务"
    verify_containers

    show_step 8 "验证 HTTPS 并完成恢复"
    verify_https || die "HTTPS 验证失败，恢复安装不会被标记为成功。"
    finalize_credentials_file
    write_install_lock
    remove_recovery_credentials_file
    INSTALL_SUCCEEDED="true"
    print_credentials_summary
}

main() {
    cd "$SCRIPT_DIR"
    unset GITHUB_TOKEN GIT_ASKPASS GIT_TERMINAL_PROMPT || true
    banner

    if [ "$INSTALL_MODE" = "resume" ]; then
        resume_installation
        return 0
    fi

    show_step 1 "检查服务器环境"
    require_root
    require_runtime
    acquire_install_lock
    guard_existing_installation
    success "环境、权限、并发锁和重复安装保护检查通过。"

    show_step 2 "配置站点信息"
    prompt_site_name
    prompt_domain
    prompt_admin_email
    prompt_admin_password
    confirm_install

    show_step 3 "生成安全凭据"
    generate_credentials

    show_step 4 "写入并校验配置"
    write_env_file
    write_config_file
    write_appprofile_file
    write_compose_override
    write_recovery_credentials_file
    validate_compose_config

    show_step 5 "构建 Docker 镜像"
    build_images
    success "Docker 镜像构建完成。"

    show_step 6 "初始化数据库"
    docker_compose_up mariadb redis
    wait_for_health mariadb 240
    wait_for_health redis 120
    docker_compose_up app nginx caddy scheduler
    ensure_app_autoload
    run_init_command Migration new
    run_init_command Migration latest
    run_init_command Tool importSetting
    ensure_user_ga_enable_column

    show_step 7 "创建管理员"
    create_admin

    show_step 8 "验证站点"
    verify_containers
    verify_https || die "HTTPS 验证失败，安装不会被标记为成功。"
    finalize_credentials_file
    write_install_lock
    remove_recovery_credentials_file
    INSTALL_SUCCEEDED="true"
    print_credentials_summary
}

if [ -n "${BASH_SOURCE[0]:-}" ] && [ "${BASH_SOURCE[0]:-}" = "$0" ]; then
    main "$@"
fi
