#!/usr/bin/env bash
set -euo pipefail

APP_CONFIG_EXAMPLE="config/.config.example.php"
APP_PROFILE_EXAMPLE="config/appprofile.example.php"
APP_CONFIG_FILE="config/.config.php"
APP_PROFILE_FILE="config/appprofile.php"
ENV_FILE=".env"

BUILD_STASH_DIR=""
STASHED_PATHS=()
STASHED_FILES=()

die() {
    echo "ERROR: $*" >&2
    exit 1
}

step() {
    echo
    echo "==> $*"
}

trim() {
    local value="$*"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf "%s" "$value"
}

confirm() {
    local prompt="$1"
    local answer

    while true; do
        read -r -p "${prompt} [y/N]: " answer
        case "$(trim "$answer")" in
            y|Y|yes|YES) return 0 ;;
            n|N|no|NO|"") return 1 ;;
            *) echo "Please answer y or n." ;;
        esac
    done
}

prompt_value() {
    local variable_name="$1"
    local label="$2"
    local default_value="${3:-}"
    local value

    if [ -n "$default_value" ]; then
        read -r -p "${label} [${default_value}]: " value
        value="$(trim "$value")"
        if [ -z "$value" ]; then
            value="$default_value"
        fi
    else
        read -r -p "${label}: " value
        value="$(trim "$value")"
    fi

    printf -v "$variable_name" "%s" "$value"
}

prompt_secret() {
    local variable_name="$1"
    local label="$2"
    local optional="${3:-false}"
    local value

    while true; do
        if [ -t 0 ]; then
            read -r -s -p "${label}: " value
            echo
        else
            read -r -p "${label}: " value
        fi

        if [ -n "$value" ] || [ "$optional" = "true" ]; then
            printf -v "$variable_name" "%s" "$value"
            return 0
        fi

        echo "${label} cannot be empty."
    done
}

require_command() {
    local command_name="$1"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        die "Required command not found: ${command_name}"
    fi
}

validate_inputs() {
    [ -n "$APP_DOMAIN" ] || die "Domain name cannot be empty."
    [ -n "$APP_NAME" ] || die "App/site name cannot be empty."
    [ -n "$DB_DATABASE" ] || die "Database name cannot be empty."
    [ -n "$DB_USERNAME" ] || die "Database username cannot be empty."
    [ -n "$DB_PASSWORD" ] || die "Database password cannot be empty."
    [ -n "$DB_ROOT_PASSWORD" ] || die "Database root password cannot be empty."
    [ -n "$ADMIN_EMAIL" ] || die "Admin email cannot be empty."
    [ -n "$ADMIN_PASSWORD" ] || die "Admin password cannot be empty."

    case "$HTTP_PORT" in
        ""|*[!0-9]*) die "HTTP port must be numeric." ;;
    esac

    if [ "$HTTP_PORT" -lt 1 ] || [ "$HTTP_PORT" -gt 65535 ]; then
        die "HTTP port must be between 1 and 65535."
    fi

    case "$ADMIN_EMAIL" in
        *@*.*) ;;
        *) die "Admin email does not look valid." ;;
    esac
}

normalize_domain() {
    APP_DOMAIN="${APP_DOMAIN#http://}"
    APP_DOMAIN="${APP_DOMAIN#https://}"
    APP_DOMAIN="${APP_DOMAIN%%/*}"
}

make_base_url() {
    if [ "$HTTP_PORT" = "80" ]; then
        BASE_URL="http://${APP_DOMAIN}"
    else
        BASE_URL="http://${APP_DOMAIN}:${HTTP_PORT}"
    fi
}

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return 0
    fi

    if [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
        od -An -N32 -tx1 /dev/urandom | tr -d " \n"
        return 0
    fi

    die "Unable to generate a secure random secret. Install openssl or ensure /dev/urandom and od are available."
}

dotenv_quote() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

php_string() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

backup_file() {
    local path="$1"
    local backup_path
    backup_path="${path}.bak.$(date +%Y%m%d%H%M%S)"
    cp -p "$path" "$backup_path"
    echo "Backed up ${path} to ${backup_path}"
}

prepare_overwrite() {
    local path="$1"

    if [ -e "$path" ]; then
        if confirm "${path} already exists. Back it up and overwrite it?"; then
            backup_file "$path"
        else
            die "Cannot continue without overwriting ${path}."
        fi
    fi
}

write_env_file() {
    local temp_file
    temp_file="$(mktemp)"

    {
        echo "# Generated by install.sh. Do not commit this file."
        printf "APP_DOMAIN=%s\n" "$(dotenv_quote "$APP_DOMAIN")"
        printf "APP_NAME=%s\n" "$(dotenv_quote "$APP_NAME")"
        printf "HTTP_PORT=%s\n" "$(dotenv_quote "$HTTP_PORT")"
        echo
        printf "DB_DATABASE=%s\n" "$(dotenv_quote "$DB_DATABASE")"
        printf "DB_USERNAME=%s\n" "$(dotenv_quote "$DB_USERNAME")"
        printf "DB_PASSWORD=%s\n" "$(dotenv_quote "$DB_PASSWORD")"
        printf "DB_ROOT_PASSWORD=%s\n" "$(dotenv_quote "$DB_ROOT_PASSWORD")"
        echo
        printf "REDIS_PASSWORD=%s\n" "$(dotenv_quote "$REDIS_PASSWORD")"
        echo
        printf "TZ=%s\n" "$(dotenv_quote "$TZ")"
        echo
        printf "ADMIN_EMAIL=%s\n" "$(dotenv_quote "$ADMIN_EMAIL")"
        printf "ADMIN_PASSWORD=%s\n" "$(dotenv_quote "$ADMIN_PASSWORD")"
    } > "$temp_file"

    chmod 0600 "$temp_file"
    mv "$temp_file" "$ENV_FILE"
}

write_config_file() {
    local temp_file
    local app_key
    local mu_key
    local key_value
    local mu_key_value
    local app_name_value
    local base_url_value
    local db_host_value
    local db_socket_value
    local db_database_value
    local db_username_value
    local db_password_value
    local db_port_value
    local redis_host_value
    local redis_port_value
    local redis_username_value
    local redis_password_value
    local timezone_value

    app_key="$(generate_secret)"
    mu_key="$(generate_secret)"
    key_value="$(php_string "$app_key")"
    mu_key_value="$(php_string "$mu_key")"
    app_name_value="$(php_string "$APP_NAME")"
    base_url_value="$(php_string "$BASE_URL")"
    db_host_value="$(php_string "mariadb")"
    db_socket_value="$(php_string "")"
    db_database_value="$(php_string "$DB_DATABASE")"
    db_username_value="$(php_string "$DB_USERNAME")"
    db_password_value="$(php_string "$DB_PASSWORD")"
    db_port_value="$(php_string "3306")"
    redis_host_value="$(php_string "redis")"
    redis_port_value="6379"
    redis_username_value="$(php_string "")"
    redis_password_value="$(php_string "$REDIS_PASSWORD")"
    timezone_value="$(php_string "$TZ")"

    temp_file="$(mktemp)"

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            "\$_ENV['key'] ="*) printf "\$_ENV['key'] = %s;     // Generated by install.sh\n" "$key_value" ;;
            "\$_ENV['appName'] ="*) printf "\$_ENV['appName'] = %s;         // Generated by install.sh\n" "$app_name_value" ;;
            "\$_ENV['baseUrl'] ="*) printf "\$_ENV['baseUrl'] = %s; // Generated by install.sh\n" "$base_url_value" ;;
            "\$_ENV['muKey'] ="*) printf "\$_ENV['muKey'] = %s;           // Generated by install.sh\n" "$mu_key_value" ;;
            "\$_ENV['db_host'] ="*) printf "\$_ENV['db_host'] = %s;\n" "$db_host_value" ;;
            "\$_ENV['db_socket'] ="*) printf "\$_ENV['db_socket'] = %s;\n" "$db_socket_value" ;;
            "\$_ENV['db_database'] ="*) printf "\$_ENV['db_database'] = %s; // Generated by install.sh\n" "$db_database_value" ;;
            "\$_ENV['db_username'] ="*) printf "\$_ENV['db_username'] = %s;    // Generated by install.sh\n" "$db_username_value" ;;
            "\$_ENV['db_password'] ="*) printf "\$_ENV['db_password'] = %s; // Generated by install.sh\n" "$db_password_value" ;;
            "\$_ENV['db_port'] ="*) printf "\$_ENV['db_port'] = %s;        // Generated by install.sh\n" "$db_port_value" ;;
            "\$_ENV['redis_host'] ="*) printf "\$_ENV['redis_host'] = %s;    // Generated by install.sh\n" "$redis_host_value" ;;
            "\$_ENV['redis_port'] ="*) printf "\$_ENV['redis_port'] = %s;           // Generated by install.sh\n" "$redis_port_value" ;;
            "\$_ENV['redis_username'] ="*) printf "\$_ENV['redis_username'] = %s;         // Generated by install.sh\n" "$redis_username_value" ;;
            "\$_ENV['redis_password'] ="*) printf "\$_ENV['redis_password'] = %s;         // Generated by install.sh\n" "$redis_password_value" ;;
            "\$_ENV['timeZone'] ="*) printf "\$_ENV['timeZone'] = %s;        // Generated by install.sh\n" "$timezone_value" ;;
            *) printf "%s\n" "$line" ;;
        esac
    done < "$APP_CONFIG_EXAMPLE" > "$temp_file"

    chmod 0644 "$temp_file"
    mv "$temp_file" "$APP_CONFIG_FILE"
}

write_appprofile_file() {
    cp "$APP_PROFILE_EXAMPLE" "$APP_PROFILE_FILE"
    chmod 0644 "$APP_PROFILE_FILE"
}

export_compose_environment() {
    export APP_DOMAIN APP_NAME HTTP_PORT
    export DB_DATABASE DB_USERNAME DB_PASSWORD DB_ROOT_PASSWORD
    export REDIS_PASSWORD TZ
}

stash_for_build() {
    local path="$1"
    local stash_file

    [ -e "$path" ] || return 0

    if [ -z "$BUILD_STASH_DIR" ]; then
        BUILD_STASH_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sspanel-install-build.XXXXXX")"
    fi

    stash_file="${BUILD_STASH_DIR}/$(printf "%s" "$path" | tr "/\\" "__")"
    mv "$path" "$stash_file"
    STASHED_PATHS+=("$path")
    STASHED_FILES+=("$stash_file")
}

restore_build_files() {
    local index
    local path
    local stash_file

    for index in "${!STASHED_PATHS[@]}"; do
        path="${STASHED_PATHS[$index]}"
        stash_file="${STASHED_FILES[$index]}"

        if [ -e "$stash_file" ]; then
            mkdir -p "$(dirname "$path")"
            mv "$stash_file" "$path"
        fi
    done

    if [ -n "$BUILD_STASH_DIR" ] && [ -d "$BUILD_STASH_DIR" ]; then
        rmdir "$BUILD_STASH_DIR" 2>/dev/null || true
    fi

    BUILD_STASH_DIR=""
    STASHED_PATHS=()
    STASHED_FILES=()
}

check_existing_containers() {
    local existing
    existing="$(docker compose ps -a --format '{{.Name}}' 2>/dev/null || true)"

    if [ -n "$existing" ]; then
        echo "Existing Docker Compose containers were found:"
        echo "$existing"
        if ! confirm "Continue without deleting existing containers or volumes?"; then
            die "Installation cancelled."
        fi
    fi
}

wait_for_health() {
    local service="$1"
    local timeout_seconds="${2:-180}"
    local start_time
    local container_id
    local status

    start_time="$(date +%s)"

    while true; do
        container_id="$(docker compose ps -q "$service" | sed -n '1p')"

        if [ -n "$container_id" ]; then
            status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"

            case "$status" in
                healthy|running)
                    echo "${service} is ready."
                    return 0
                    ;;
                unhealthy|exited|dead)
                    die "${service} is ${status}. Check logs with: docker compose logs ${service}"
                    ;;
            esac
        fi

        if [ $(( "$(date +%s)" - start_time )) -ge "$timeout_seconds" ]; then
            die "Timed out waiting for ${service} readiness."
        fi

        sleep 3
    done
}

run_init_command() {
    echo "+ docker compose exec -T app php xcat $*"
    docker compose exec -T app php xcat "$@"
}

ensure_app_autoload() {
    echo "+ docker compose exec -T app test -f vendor/autoload.php"
    if ! docker compose exec -T app test -f vendor/autoload.php; then
        die "Missing vendor/autoload.php in the app container. Rebuild the image and make sure composer install completes before initialization."
    fi
}

main() {
    step "Checking prerequisites"
    require_command docker

    if ! docker compose version >/dev/null 2>&1; then
        die "Docker Compose v2 is required. Use the 'docker compose' plugin, not docker-compose."
    fi

    [ -f "$APP_CONFIG_EXAMPLE" ] || die "Missing ${APP_CONFIG_EXAMPLE}"
    [ -f "$APP_PROFILE_EXAMPLE" ] || die "Missing ${APP_PROFILE_EXAMPLE}"

    step "Checking existing generated files"
    prepare_overwrite "$ENV_FILE"
    prepare_overwrite "$APP_CONFIG_FILE"
    prepare_overwrite "$APP_PROFILE_FILE"

    step "Collecting deployment settings"
    prompt_value APP_DOMAIN "Domain name, without http:// or https://"
    normalize_domain
    prompt_value APP_NAME "App/site name" "SSPanel-UIM"
    prompt_value HTTP_PORT "HTTP port" "80"
    prompt_value DB_DATABASE "Database name" "sspanel"
    prompt_value DB_USERNAME "Database username" "sspanel"
    prompt_secret DB_PASSWORD "Database password"
    prompt_secret DB_ROOT_PASSWORD "Database root password"
    prompt_secret REDIS_PASSWORD "Redis password (optional)" "true"
    prompt_value ADMIN_EMAIL "Admin email"
    prompt_secret ADMIN_PASSWORD "Admin password"
    prompt_value TZ "Timezone" "Asia/Shanghai"

    validate_inputs
    make_base_url

    step "Generating Docker and application configuration"
    write_env_file
    write_config_file
    write_appprofile_file
    export_compose_environment

    check_existing_containers

    trap restore_build_files EXIT

    step "Building Docker image"
    stash_for_build "$ENV_FILE"
    stash_for_build "$APP_CONFIG_FILE"
    stash_for_build "$APP_PROFILE_FILE"
    docker compose build
    restore_build_files

    step "Starting MariaDB and Redis"
    docker compose up -d mariadb redis
    wait_for_health mariadb 240
    wait_for_health redis 120

    step "Starting application services"
    docker compose up -d app nginx scheduler

    step "Checking Composer dependencies"
    ensure_app_autoload

    step "Initializing database"
    run_init_command Migration new
    run_init_command Migration latest
    run_init_command Tool importSetting

    step "Creating admin user"
    if docker compose exec -T app php xcat Tool createAdmin "$ADMIN_EMAIL" "$ADMIN_PASSWORD"; then
        echo "Admin user creation command completed."
    else
        echo "WARNING: Admin user creation failed. If the admin already exists, you can continue; otherwise check: docker compose logs app" >&2
    fi

    step "Installation complete"
    echo "Access URL: ${BASE_URL}"
    echo "Admin email: ${ADMIN_EMAIL}"
    echo
    echo "Useful commands:"
    echo "  docker compose ps"
    echo "  docker compose logs -f app"
    echo "  docker compose logs -f nginx"
    echo "  docker compose logs -f scheduler"
    echo "  docker compose down"
}

main "$@"
