#!/usr/bin/env bash
set -euo pipefail

APP_CONFIG_EXAMPLE="config/.config.example.php"
APP_PROFILE_EXAMPLE="config/appprofile.example.php"
APP_CONFIG_FILE="config/.config.php"
APP_PROFILE_FILE="config/appprofile.php"
ENV_FILE=".env"
COMPOSE_OVERRIDE_FILE="docker-compose.override.yml"
COMPOSE_OVERRIDE_MARKER="# Generated by install.sh for SSPanel-UIM Docker HTTPS mode."
HTTPS_ENABLED="false"
HTTPS_PORT="443"
CADDY_SITE_ADDRESS="http://:80"
COOKIE_SECURE="false"
BASE_URL=""
MU_KEY=""
CONFIG_WRITE="true"
APP_PROFILE_WRITE="true"

BUILD_STASH_DIR=""
STASHED_PATHS=()
STASHED_FILES=()

die() {
    echo "ERROR: $*" >&2
    exit 1
}

banner() {
    cat <<'EOF'
============================================================
 SSPanel-UIM Docker 一键安装向导
============================================================
本向导将会：
  - 生成 .env 和 Docker 部署配置文件
  - 生成 config/.config.php 和 config/appprofile.php
  - 构建并启动 Docker 容器
  - 执行数据库迁移和设置导入
  - 创建管理员账号

重要提醒：
  - 不会删除已有 Docker volume
  - 不会执行 docker compose down -v
  - 不要运行 docker compose down -v，除非你明确要删除数据库、Redis 数据和 Caddy 证书
============================================================
EOF
}

step() {
    echo
    echo "==> $*"
}

wizard_section() {
    echo
    echo "[$1/7] $2"
    echo "------------------------------------------------------------"
}

progress_step() {
    echo
    echo "[$1/8] $2"
    echo "------------------------------------------------------------"
}

trim() {
    local value="$*"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    printf "%s" "$value"
}

confirm() {
    local prompt="$1"
    local answer

    while true; do
        read -r -p "${prompt} [y/N]: " answer
        case "$(trim "$answer")" in
            y|Y|yes|YES) return 0 ;;
            n|N|no|NO|"") return 1 ;;
            *) echo "请输入 y 或 n。" ;;
        esac
    done
}

prompt_value() {
    local variable_name="$1"
    local label="$2"
    local default_value="${3:-}"
    local value

    if [ -n "$default_value" ]; then
        read -r -p "${label} [${default_value}]: " value
        value="$(trim "$value")"
        if [ -z "$value" ]; then
            value="$default_value"
        fi
    else
        read -r -p "${label}: " value
        value="$(trim "$value")"
    fi

    printf -v "$variable_name" "%s" "$value"
}

prompt_secret() {
    local variable_name="$1"
    local label="$2"
    local optional="${3:-false}"
    local value

    while true; do
        if [ -t 0 ]; then
            read -r -s -p "${label}: " value
            echo
        else
            read -r -p "${label}: " value
        fi

        if [ -n "$value" ] || [ "$optional" = "true" ]; then
            printf -v "$variable_name" "%s" "$value"
            return 0
        fi

        echo "${label} 不能为空。"
    done
}

prompt_secret_confirm() {
    local variable_name="$1"
    local label="$2"
    local first_value
    local second_value

    while true; do
        prompt_secret first_value "$label"
        prompt_secret second_value "请再次输入${label}"

        if [ "$first_value" = "$second_value" ]; then
            printf -v "$variable_name" "%s" "$first_value"
            return 0
        fi

        echo "两次输入不一致，请重新输入。"
    done
}

prompt_domain() {
    while true; do
        prompt_value APP_DOMAIN "域名或访问地址（不要包含 http:// 或 https://）"

        if [ -z "$APP_DOMAIN" ]; then
            echo "域名不能为空。"
            continue
        fi

        case "$APP_DOMAIN" in
            http://*|https://*)
                echo "请只输入域名、IP 或主机名，不要包含 http:// 或 https://。"
                continue
                ;;
        esac

        if [[ "$APP_DOMAIN" =~ [[:space:]/] ]]; then
            echo "域名或访问地址不能包含空格或路径。"
            continue
        fi

        if [ "$HTTPS_ENABLED" = "true" ] && ! [[ "$APP_DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$ ]]; then
            echo "HTTPS 模式需要可公开解析的域名，例如 example.com。"
            continue
        fi

        return 0
    done
}

require_command() {
    local command_name="$1"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        if [ "$command_name" = "docker" ]; then
            die "未找到 docker 命令。请先安装 Docker Engine，并确认当前用户可以执行 docker。"
        fi

        die "Required command not found: ${command_name}"
    fi
}

validate_inputs() {
    case "$HTTPS_ENABLED" in
        true|false) ;;
        *) die "HTTPS mode must be true or false." ;;
    esac

    [ -n "$APP_DOMAIN" ] || die "域名不能为空。"
    [ -n "$APP_NAME" ] || die "站点名称不能为空。"
    [ -n "$DB_DATABASE" ] || die "数据库名不能为空。"
    [ -n "$DB_USERNAME" ] || die "数据库用户名不能为空。"
    [ -n "$DB_PASSWORD" ] || die "数据库密码不能为空。"
    [ -n "$DB_ROOT_PASSWORD" ] || die "数据库 root 密码不能为空。"
    [ -n "$ADMIN_EMAIL" ] || die "管理员邮箱不能为空。"
    [ -n "$ADMIN_PASSWORD" ] || die "管理员密码不能为空。"

    case "$APP_DOMAIN" in
        http://*|https://*) die "域名不要包含 http:// 或 https://。" ;;
    esac

    if [[ "$APP_DOMAIN" =~ [[:space:]/] ]]; then
        die "域名或访问地址不能包含空格或路径。"
    fi

    if [ "$HTTPS_ENABLED" = "true" ] && ! [[ "$APP_DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$ ]]; then
        die "HTTPS 模式需要可公开解析的域名，例如 example.com。"
    fi

    case "$HTTP_PORT" in
        ""|*[!0-9]*) die "HTTP 端口必须是数字。" ;;
    esac

    if [ "$HTTP_PORT" -lt 1 ] || [ "$HTTP_PORT" -gt 65535 ]; then
        die "HTTP 端口必须在 1 到 65535 之间。"
    fi

    case "$HTTPS_PORT" in
        ""|*[!0-9]*) die "HTTPS 端口必须是数字。" ;;
    esac

    if [ "$HTTPS_PORT" -lt 1 ] || [ "$HTTPS_PORT" -gt 65535 ]; then
        die "HTTPS 端口必须在 1 到 65535 之间。"
    fi

    case "$ADMIN_EMAIL" in
        *@*.*) ;;
        *) die "管理员邮箱格式看起来不正确。" ;;
    esac

    if [ "$HTTPS_ENABLED" = "true" ] && { [ "$HTTP_PORT" != "80" ] || [ "$HTTPS_PORT" != "443" ]; }; then
        die "HTTPS 模式需要公网 HTTP 80 和 HTTPS 443 端口用于 Let's Encrypt 验证。"
    fi

    if [ -n "$MU_KEY" ] && [[ "$MU_KEY" =~ [[:space:]] ]]; then
        die "muKey 不能包含空白字符。"
    fi
}

normalize_domain() {
    APP_DOMAIN="${APP_DOMAIN#http://}"
    APP_DOMAIN="${APP_DOMAIN#https://}"
    APP_DOMAIN="${APP_DOMAIN%%/*}"
}

make_base_url() {
    if [ "$HTTPS_ENABLED" = "true" ]; then
        CADDY_SITE_ADDRESS="$APP_DOMAIN"
        COOKIE_SECURE="true"
        BASE_URL="https://${APP_DOMAIN}"
    else
        CADDY_SITE_ADDRESS="http://:80"
        COOKIE_SECURE="false"
        if [ "$HTTP_PORT" = "80" ]; then
            BASE_URL="http://${APP_DOMAIN}"
        else
            BASE_URL="http://${APP_DOMAIN}:${HTTP_PORT}"
        fi
    fi
}

print_final_summary() {
    local redis_state
    local mu_key_state

    if [ -n "$REDIS_PASSWORD" ]; then
        redis_state="已配置（不显示）"
    else
        redis_state="未设置"
    fi

    if [ -n "$MU_KEY" ]; then
        mu_key_state="自定义值已输入（不显示）"
    else
        mu_key_state="留空，安装时自动生成"
    fi

    wizard_section 7 "配置确认"
    echo "部署模式: $([ "$HTTPS_ENABLED" = "true" ] && echo "HTTPS / Caddy 自动 SSL" || echo "HTTP-only")"
    echo "访问地址: ${BASE_URL}"
    echo "域名/主机: ${APP_DOMAIN}"
    echo "站点名称: ${APP_NAME}"
    echo "HTTP 端口: ${HTTP_PORT}"
    if [ "$HTTPS_ENABLED" = "true" ]; then
        echo "HTTPS 端口: ${HTTPS_PORT}"
    fi
    echo "数据库名: ${DB_DATABASE}"
    echo "数据库用户: ${DB_USERNAME}"
    echo "数据库密码: ********"
    echo "数据库 root 密码: ********"
    echo "Redis 密码: ${redis_state}"
    echo "管理员邮箱: ${ADMIN_EMAIL}"
    echo "管理员密码: ********"
    echo "muKey: ${mu_key_state}"
    echo "时区: ${TZ}"
    echo
    echo "继续后才会写入 .env / config 文件并启动 Docker 服务。"
}

print_https_warning() {
    if [ "$HTTPS_ENABLED" = "true" ]; then
        echo
        echo "已选择 HTTPS 模式。"
        echo "HTTPS 模式适合生产环境，并会通过 Caddy 自动申请和续期 Let's Encrypt 证书。"
        echo "继续前请确认："
        echo "  - 域名 DNS A/AAAA 记录已经指向本服务器"
        echo "  - 公网 80 和 443 端口已经开放"
        echo "  - 服务器上没有其他服务占用 80/443"
        echo "  - Cloudflare 用户如遇证书签发失败，可先切换为 DNS-only"
        echo "本阶段 HTTPS 模式会固定使用 HTTP_PORT=80 和 HTTPS_PORT=443。"
    else
        echo
        echo "已选择 HTTP-only 模式。"
        echo "HTTP-only 适合测试、内网环境，或前面已经有其他反向代理的用户。"
        echo "生成的应用配置会设置 cookie_secure=false，确保 HTTP 登录可用。"
    fi
}

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return 0
    fi

    if [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
        od -An -N32 -tx1 /dev/urandom | tr -d " \n"
        return 0
    fi

    die "Unable to generate a secure random secret. Install openssl or ensure /dev/urandom and od are available."
}

dotenv_quote() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

php_string() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\'/\\\'}"
    printf "'%s'" "$value"
}

backup_file() {
    local path="$1"
    local backup_path
    backup_path="${path}.bak.$(date +%Y%m%d%H%M%S)"
    cp -p "$path" "$backup_path"
    echo "Backed up ${path} to ${backup_path}"
}

prepare_overwrite() {
    local path="$1"

    if [ -e "$path" ]; then
        if confirm "检测到 ${path} 已存在。是否先备份再覆盖？"; then
            backup_file "$path"
        else
            die "用户选择不覆盖 ${path}，安装已安全停止，未修改该文件。"
        fi
    fi
}

prepare_config_file() {
    CONFIG_WRITE="true"

    if [ -e "$APP_CONFIG_FILE" ]; then
        if confirm "检测到 ${APP_CONFIG_FILE} 已存在。是否先备份再重新生成？"; then
            backup_file "$APP_CONFIG_FILE"
        else
            CONFIG_WRITE="false"
            warn_existing_config_values
        fi
    fi
}

prepare_appprofile_file() {
    APP_PROFILE_WRITE="true"

    if [ -e "$APP_PROFILE_FILE" ]; then
        if confirm "检测到 ${APP_PROFILE_FILE} 已存在。是否先备份再重新生成？"; then
            backup_file "$APP_PROFILE_FILE"
        else
            APP_PROFILE_WRITE="false"
            echo "保留现有 ${APP_PROFILE_FILE}，不会修改该文件。"
        fi
    fi
}

warn_existing_config_values() {
    echo "WARNING: 保留现有 ${APP_CONFIG_FILE}，不会修改该文件。" >&2
    echo "WARNING: 请手动确认当前部署模式需要的值：" >&2
    printf "  \$_ENV['baseUrl'] = %s;\n" "$(php_string "$BASE_URL")" >&2
    printf "  \$_ENV['cookie_secure'] = %s;\n" "$COOKIE_SECURE" >&2
    echo "WARNING: 现有 muKey 保持不变。如手动修改 muKey，请同步更新所有节点侧配置。" >&2
}

write_https_compose_override() {
    local temp_file

    if [ -e "$COMPOSE_OVERRIDE_FILE" ] && ! grep -Fq "$COMPOSE_OVERRIDE_MARKER" "$COMPOSE_OVERRIDE_FILE"; then
        if confirm "${COMPOSE_OVERRIDE_FILE} already exists and was not generated by install.sh. Back it up and replace it for HTTPS mode?"; then
            backup_file "$COMPOSE_OVERRIDE_FILE"
        else
            die "Cannot continue in HTTPS mode without managing ${COMPOSE_OVERRIDE_FILE}."
        fi
    fi

    temp_file="$(mktemp)"

    {
        echo "$COMPOSE_OVERRIDE_MARKER"
        echo "services:"
        echo "  caddy:"
        echo "    ports:"
        echo "      - \"\${HTTPS_PORT:-443}:443\""
    } > "$temp_file"

    chmod 0644 "$temp_file"
    mv "$temp_file" "$COMPOSE_OVERRIDE_FILE"
}

remove_https_compose_override() {
    if [ ! -e "$COMPOSE_OVERRIDE_FILE" ]; then
        return 0
    fi

    if grep -Fq "$COMPOSE_OVERRIDE_MARKER" "$COMPOSE_OVERRIDE_FILE"; then
        rm -f "$COMPOSE_OVERRIDE_FILE"
        echo "Removed generated ${COMPOSE_OVERRIDE_FILE}; HTTP-only mode will not publish port 443."
        return 0
    fi

    echo "WARNING: ${COMPOSE_OVERRIDE_FILE} exists and was not generated by install.sh." >&2
    echo "WARNING: HTTP-only base Compose no longer publishes port 443, but your custom override may still change published ports." >&2

    if confirm "Keep custom ${COMPOSE_OVERRIDE_FILE} for HTTP-only mode?"; then
        echo "Keeping custom ${COMPOSE_OVERRIDE_FILE}. Review it manually if HTTP-only mode must not publish port 443."
        return 0
    fi

    if confirm "Back up and remove custom ${COMPOSE_OVERRIDE_FILE} for HTTP-only mode?"; then
        backup_file "$COMPOSE_OVERRIDE_FILE"
        rm -f "$COMPOSE_OVERRIDE_FILE"
        return 0
    fi

    die "Cannot guarantee HTTP-only port behavior while unmanaged ${COMPOSE_OVERRIDE_FILE} remains active."
}

write_env_file() {
    local temp_file
    temp_file="$(mktemp)"

    {
        echo "# Generated by install.sh. Do not commit this file."
        printf "APP_DOMAIN=%s\n" "$(dotenv_quote "$APP_DOMAIN")"
        printf "APP_NAME=%s\n" "$(dotenv_quote "$APP_NAME")"
        printf "HTTPS_ENABLED=%s\n" "$(dotenv_quote "$HTTPS_ENABLED")"
        printf "HTTP_PORT=%s\n" "$(dotenv_quote "$HTTP_PORT")"
        printf "HTTPS_PORT=%s\n" "$(dotenv_quote "$HTTPS_PORT")"
        printf "CADDY_SITE_ADDRESS=%s\n" "$(dotenv_quote "$CADDY_SITE_ADDRESS")"
        echo
        printf "DB_DATABASE=%s\n" "$(dotenv_quote "$DB_DATABASE")"
        printf "DB_USERNAME=%s\n" "$(dotenv_quote "$DB_USERNAME")"
        printf "DB_PASSWORD=%s\n" "$(dotenv_quote "$DB_PASSWORD")"
        printf "DB_ROOT_PASSWORD=%s\n" "$(dotenv_quote "$DB_ROOT_PASSWORD")"
        echo
        printf "REDIS_PASSWORD=%s\n" "$(dotenv_quote "$REDIS_PASSWORD")"
        echo
        printf "TZ=%s\n" "$(dotenv_quote "$TZ")"
        echo
        printf "ADMIN_EMAIL=%s\n" "$(dotenv_quote "$ADMIN_EMAIL")"
        printf "ADMIN_PASSWORD=%s\n" "$(dotenv_quote "$ADMIN_PASSWORD")"
    } > "$temp_file"

    chmod 0600 "$temp_file"
    mv "$temp_file" "$ENV_FILE"
}

write_config_file() {
    local temp_file
    local app_key
    local mu_key
    local key_value
    local mu_key_value
    local app_name_value
    local base_url_value
    local cookie_secure_value
    local db_host_value
    local db_socket_value
    local db_database_value
    local db_username_value
    local db_password_value
    local db_port_value
    local redis_host_value
    local redis_port_value
    local redis_username_value
    local redis_password_value
    local timezone_value

    [ "$CONFIG_WRITE" = "true" ] || return 0

    app_key="$(generate_secret)"
    if [ -n "$MU_KEY" ]; then
        mu_key="$MU_KEY"
    else
        mu_key="$(generate_secret)"
    fi
    key_value="$(php_string "$app_key")"
    mu_key_value="$(php_string "$mu_key")"
    app_name_value="$(php_string "$APP_NAME")"
    base_url_value="$(php_string "$BASE_URL")"
    cookie_secure_value="$COOKIE_SECURE"
    db_host_value="$(php_string "mariadb")"
    db_socket_value="$(php_string "")"
    db_database_value="$(php_string "$DB_DATABASE")"
    db_username_value="$(php_string "$DB_USERNAME")"
    db_password_value="$(php_string "$DB_PASSWORD")"
    db_port_value="$(php_string "3306")"
    redis_host_value="$(php_string "redis")"
    redis_port_value="6379"
    redis_username_value="$(php_string "")"
    redis_password_value="$(php_string "$REDIS_PASSWORD")"
    timezone_value="$(php_string "$TZ")"

    temp_file="$(mktemp)"

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            "\$_ENV['key'] ="*) printf "\$_ENV['key'] = %s;     // Generated by install.sh\n" "$key_value" ;;
            "\$_ENV['appName'] ="*) printf "\$_ENV['appName'] = %s;         // Generated by install.sh\n" "$app_name_value" ;;
            "\$_ENV['baseUrl'] ="*) printf "\$_ENV['baseUrl'] = %s; // Generated by install.sh\n\$_ENV['cookie_secure'] = %s;        // Generated by install.sh for Docker installs\n" "$base_url_value" "$cookie_secure_value" ;;
            "\$_ENV['muKey'] ="*) printf "\$_ENV['muKey'] = %s;           // Generated by install.sh\n" "$mu_key_value" ;;
            "\$_ENV['db_host'] ="*) printf "\$_ENV['db_host'] = %s;\n" "$db_host_value" ;;
            "\$_ENV['db_socket'] ="*) printf "\$_ENV['db_socket'] = %s;\n" "$db_socket_value" ;;
            "\$_ENV['db_database'] ="*) printf "\$_ENV['db_database'] = %s; // Generated by install.sh\n" "$db_database_value" ;;
            "\$_ENV['db_username'] ="*) printf "\$_ENV['db_username'] = %s;    // Generated by install.sh\n" "$db_username_value" ;;
            "\$_ENV['db_password'] ="*) printf "\$_ENV['db_password'] = %s; // Generated by install.sh\n" "$db_password_value" ;;
            "\$_ENV['db_port'] ="*) printf "\$_ENV['db_port'] = %s;        // Generated by install.sh\n" "$db_port_value" ;;
            "\$_ENV['redis_host'] ="*) printf "\$_ENV['redis_host'] = %s;    // Generated by install.sh\n" "$redis_host_value" ;;
            "\$_ENV['redis_port'] ="*) printf "\$_ENV['redis_port'] = %s;           // Generated by install.sh\n" "$redis_port_value" ;;
            "\$_ENV['redis_username'] ="*) printf "\$_ENV['redis_username'] = %s;         // Generated by install.sh\n" "$redis_username_value" ;;
            "\$_ENV['redis_password'] ="*) printf "\$_ENV['redis_password'] = %s;         // Generated by install.sh\n" "$redis_password_value" ;;
            "\$_ENV['timeZone'] ="*) printf "\$_ENV['timeZone'] = %s;        // Generated by install.sh\n" "$timezone_value" ;;
            *) printf "%s\n" "$line" ;;
        esac
    done < "$APP_CONFIG_EXAMPLE" > "$temp_file"

    chmod 0644 "$temp_file"
    mv "$temp_file" "$APP_CONFIG_FILE"
}

write_appprofile_file() {
    [ "$APP_PROFILE_WRITE" = "true" ] || return 0

    cp "$APP_PROFILE_EXAMPLE" "$APP_PROFILE_FILE"
    chmod 0644 "$APP_PROFILE_FILE"
}

export_compose_environment() {
    export APP_DOMAIN APP_NAME HTTPS_ENABLED HTTP_PORT HTTPS_PORT CADDY_SITE_ADDRESS
    export DB_DATABASE DB_USERNAME DB_PASSWORD DB_ROOT_PASSWORD
    export REDIS_PASSWORD TZ
}

stash_for_build() {
    local path="$1"
    local stash_file

    [ -e "$path" ] || return 0

    if [ -z "$BUILD_STASH_DIR" ]; then
        BUILD_STASH_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sspanel-install-build.XXXXXX")"
    fi

    stash_file="${BUILD_STASH_DIR}/$(printf "%s" "$path" | tr "/\\" "__")"
    mv "$path" "$stash_file"
    STASHED_PATHS+=("$path")
    STASHED_FILES+=("$stash_file")
}

restore_build_files() {
    local index
    local path
    local stash_file

    for index in "${!STASHED_PATHS[@]}"; do
        path="${STASHED_PATHS[$index]}"
        stash_file="${STASHED_FILES[$index]}"

        if [ -e "$stash_file" ]; then
            mkdir -p "$(dirname "$path")"
            mv "$stash_file" "$path"
        fi
    done

    if [ -n "$BUILD_STASH_DIR" ] && [ -d "$BUILD_STASH_DIR" ]; then
        rmdir "$BUILD_STASH_DIR" 2>/dev/null || true
    fi

    BUILD_STASH_DIR=""
    STASHED_PATHS=()
    STASHED_FILES=()
}

check_existing_containers() {
    local existing
    existing="$(docker compose ps -a --format '{{.Name}}' 2>/dev/null || true)"

    if [ -n "$existing" ]; then
        echo "检测到当前目录已有 Docker Compose 容器："
        echo "$existing"
        echo "安装脚本不会删除容器或 volume；继续会尝试复用/更新这些服务。"
        if ! confirm "是否继续？"; then
            die "安装已取消。未删除任何容器或 volume。"
        fi
    fi
}

docker_compose_up() {
    local services=("$@")

    if ! docker compose up -d "${services[@]}"; then
        echo "ERROR: Docker Compose 启动失败：${services[*]}" >&2
        echo "请查看上方 Docker 输出和以下日志命令：" >&2
        printf "  docker compose logs %s\n" "${services[@]}" >&2

        case " ${services[*]} " in
            *" caddy "*)
                echo "如果 Caddy 启动失败，请检查 80/443 端口是否被其他服务占用。" >&2
                ;;
        esac

        exit 1
    fi
}

wait_for_health() {
    local service="$1"
    local timeout_seconds="${2:-180}"
    local start_time
    local container_id
    local status

    start_time="$(date +%s)"

    while true; do
        container_id="$(docker compose ps -q "$service" | sed -n '1p')"

        if [ -n "$container_id" ]; then
            status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"

            case "$status" in
                healthy|running)
                    echo "${service} is ready."
                    return 0
                    ;;
                unhealthy|exited|dead)
                    die "${service} 状态为 ${status}。请查看日志：docker compose logs ${service}"
                    ;;
            esac
        fi

        if [ $(( "$(date +%s)" - start_time )) -ge "$timeout_seconds" ]; then
            die "等待 ${service} 就绪超时。请查看日志：docker compose logs ${service}"
        fi

        sleep 3
    done
}

run_init_command() {
    echo "+ docker compose exec -T app php xcat $*"
    docker compose exec -T app php xcat "$@"
}

ensure_app_autoload() {
    echo "+ docker compose exec -T app test -f vendor/autoload.php"
    if ! docker compose exec -T app test -f vendor/autoload.php; then
        die "Missing vendor/autoload.php in the app container. Rebuild the image and make sure composer install completes before initialization."
    fi
}

main() {
    banner

    step "检查前置条件"
    require_command docker

    if ! docker compose version >/dev/null 2>&1; then
        die "未找到 Docker Compose v2 插件。当前脚本使用 'docker compose'，不是旧版 'docker-compose'。"
    fi

    [ -f "$APP_CONFIG_EXAMPLE" ] || die "Missing ${APP_CONFIG_EXAMPLE}"
    [ -f "$APP_PROFILE_EXAMPLE" ] || die "Missing ${APP_PROFILE_EXAMPLE}"

    wizard_section 1 "部署模式"
    echo "HTTP-only：适合测试、内网，或已经在前面使用其他反向代理的环境。"
    echo "HTTPS：推荐生产环境使用，Caddy 会自动申请和续期 Let's Encrypt 证书。"
    if confirm "是否启用 Caddy 自动 HTTPS？"; then
        HTTPS_ENABLED="true"
    else
        HTTPS_ENABLED="false"
    fi

    print_https_warning

    wizard_section 2 "站点信息"
    prompt_domain
    prompt_value APP_NAME "站点名称" "SSPanel-UIM"
    if [ "$HTTPS_ENABLED" = "true" ]; then
        HTTP_PORT="80"
        HTTPS_PORT="443"
        echo "HTTP 端口: 80"
        echo "HTTPS 端口: 443"
    else
        prompt_value HTTP_PORT "HTTP 端口" "80"
        HTTPS_PORT="443"
    fi
    prompt_value TZ "时区" "Asia/Shanghai"

    wizard_section 3 "数据库配置"
    prompt_value DB_DATABASE "数据库名" "sspanel"
    prompt_value DB_USERNAME "数据库用户名" "sspanel"
    prompt_secret DB_PASSWORD "数据库密码"
    prompt_secret DB_ROOT_PASSWORD "数据库 root 密码"

    wizard_section 4 "Redis 配置"
    echo "Redis 密码可以留空。Redis 默认只在 Docker 内部网络中使用，不会公开端口。"
    prompt_secret REDIS_PASSWORD "Redis 密码（可留空）" "true"

    wizard_section 5 "管理员账号"
    prompt_value ADMIN_EMAIL "管理员邮箱"
    prompt_secret_confirm ADMIN_PASSWORD "管理员密码"

    wizard_section 6 "节点通信密钥"
    echo "muKey 用于节点/服务端通信。留空则自动生成强随机值。"
    echo "节点接入后不要随意修改 muKey，除非同步更新所有节点配置。"
    prompt_secret MU_KEY "muKey（可留空）" "true"

    validate_inputs
    make_base_url

    print_final_summary
    if ! confirm "继续安装？"; then
        echo "安装已取消。未写入文件，未启动容器。"
        exit 0
    fi

    progress_step 1 "生成 .env"
    prepare_overwrite "$ENV_FILE"
    write_env_file
    if [ "$HTTPS_ENABLED" = "true" ]; then
        write_https_compose_override
    else
        remove_https_compose_override
    fi

    progress_step 2 "生成配置文件"
    prepare_config_file
    prepare_appprofile_file
    write_config_file
    write_appprofile_file
    export_compose_environment

    check_existing_containers

    trap restore_build_files EXIT

    progress_step 3 "构建 Docker 镜像"
    stash_for_build "$ENV_FILE"
    stash_for_build "$APP_CONFIG_FILE"
    stash_for_build "$APP_PROFILE_FILE"
    if ! docker compose build; then
        die "Docker 镜像构建失败。请查看上方 Composer/PHP/Docker 错误输出。"
    fi
    restore_build_files

    progress_step 4 "启动 MariaDB / Redis"
    docker_compose_up mariadb redis

    progress_step 5 "等待数据库和 Redis 就绪"
    wait_for_health mariadb 240
    wait_for_health redis 120

    progress_step 6 "启动应用服务"
    docker_compose_up app nginx caddy scheduler

    progress_step 7 "初始化数据库"
    ensure_app_autoload
    run_init_command Migration new
    run_init_command Migration latest
    run_init_command Tool importSetting

    progress_step 8 "创建管理员账号"
    if docker compose exec -T app php xcat Tool createAdmin "$ADMIN_EMAIL" "$ADMIN_PASSWORD"; then
        echo "管理员账号创建命令已完成。"
    else
        echo "WARNING: 管理员创建失败。如果管理员已存在可以继续使用；否则请查看：docker compose logs app" >&2
    fi

    step "安装完成"
    echo "访问地址: ${BASE_URL}"
    echo "HTTPS 状态: $([ "$HTTPS_ENABLED" = "true" ] && echo "已启用" || echo "未启用")"
    echo "管理员邮箱: ${ADMIN_EMAIL}"
    if [ "$CONFIG_WRITE" = "true" ]; then
        echo "muKey: 已写入 ${APP_CONFIG_FILE}，请妥善备份。"
    else
        echo "muKey: 现有 ${APP_CONFIG_FILE} 保持不变。"
    fi
    echo
    echo "常用命令:"
    echo "  docker compose ps"
    echo "  docker compose logs -f app"
    echo "  docker compose logs -f nginx"
    echo "  docker compose logs -f caddy"
    echo "  docker compose logs -f scheduler"
    echo "  docker compose down"
    echo
    echo "备份提醒:"
    echo "  - 备份 .env"
    echo "  - 备份 config/.config.php"
    echo "  - 备份 config/appprofile.php"
    echo "  - 定期备份数据库"
    echo
    echo "重要警告: 不要运行 docker compose down -v，除非你明确要删除数据库、Redis 数据和 Caddy 证书。"
    echo "节点提醒: config/.config.php 内的 muKey 用于节点通信，请妥善保存。"
}

main "$@"
